language: php
php:
  - '7.0'
  - '7.1'

install:
  - composer install

after_success:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash) -t 05992f7e-7481-41ec-8126-bed5edfff893